"""Generates probe10/src/p17/Q17.java: field-level sort + a second field-level feature, nested values and map keys."""
from pathlib import Path

feats = ["", "BeanToArray", "WriteNulls", "WriteClassName", "NotWriteDefaultValue", "WriteNonStringValueAsString",
         "WriteMapNullValue", "ReferenceDetection", "WriteEnumUsingToString", "WriteBigDecimalAsPlain",
         "BrowserCompatible", "WriteLongAsString", "NullAsDefaultValue", "WriteNullListAsEmpty", "IgnoreEmpty"]
typed = [("ListListB", "List<List<B>>", "new ArrayList<>(Collections.singletonList(lb()))"),
         ("AtomB", "AtomicReference<B>", "new AtomicReference<>(new B())"),
         ("OptListB", "Optional<List<B>>", "Optional.of(lb())"),
         ("ListB", "List<B>", "lb()"),
         ("ArrArrB", "B[][]", "new B[][]{{new B()}}"),
         ("MapListB", "Map<String, List<B>>", "m(\"k\", lb())"),
         ("B", "B", "new B()")]
runtime = [("List<List<B>>", "new ArrayList<>(Collections.singletonList(lb()))"), ("AtomicReference<B>", "new AtomicReference<>(new B())"),
           ("Optional<List<B>>", "Optional.of(lb())"), ("List<B>", "lb()"), ("Object[]{List<B>}", "new Object[]{lb()}"),
           ("Map{k:List<B>}", "m(\"k\", lb())"), ("JSONArray[List<B>]", "com.alibaba.fastjson2.JSONArray.of(lb())"), ("B", "new B()")]
keyshapes = [("List<B>", "lb()"), ("Optional<B>", "Optional.of(new B())"), ("AtomicReference<B>", "new AtomicReference<>(new B())"),
             ("List<List<B>>", "new ArrayList<>(Collections.singletonList(lb()))"), ("B", "new B()"), ("B[]", "new B[]{new B()}")]

L = ["""package p17;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONB;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.annotation.JSONField;
import com.alibaba.fastjson2.annotation.JSONType;
import com.alibaba.fastjson2.writer.ObjectWriterCreator;
import com.alibaba.fastjson2.writer.ObjectWriterCreatorASM;
import com.alibaba.fastjson2.writer.ObjectWriterProvider;

import java.math.BigDecimal;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;

/**
 * Round-9 probe (generated by gen_q17.py): field-level SortFieldNamesAlphabetically combined with a second field-level
 * feature, on nested values and map keys. One line per cell (channel, combo, shape) with the ASM and the reflect output,
 * so two builds can be compared cell by cell. The reflect field writer merges the field's features into the context, so it
 * is the reference for how deep field features reach.
 */
public class Q17 {
    public enum Color { RED, GREEN }

    @JSONType(alphabetic = false)
    public static class B {
        public int z = 1;
        public String n;
        public long big = 9007199254740993L;
        public Color e = Color.RED;
        public BigDecimal d = new BigDecimal("1E+3");
        public List<String> l;
        public int zero;
        public int a = 2;
    }

    static List<B> lb() {
        return new ArrayList<>(Collections.singletonList(new B()));
    }

    static <K, V> Map<K, V> m(K k, V v) {
        return new LinkedHashMap<>(Collections.singletonMap(k, v));
    }
"""]
cells = []
for i, f in enumerate(feats):
    ann = "JSONWriter.Feature.SortFieldNamesAlphabetically" + (", JSONWriter.Feature." + f if f else "")
    combo = "Sort" + ("+" + f if f else "")
    for tn, decl, init in typed:
        cn = f"T{i}_{tn}"
        L.append(f"    public static class {cn} {{ @JSONField(serializeFeatures = {{{ann}}}) public {decl} f = {init}; }}")
        cells.append(f'        c.put("{combo} | value {decl}", {cn}::new);')
    cn = f"O{i}"
    L.append(f"    public static class {cn} {{ @JSONField(serializeFeatures = {{{ann}}}) public Object f; }}")
    for rn, rinit in runtime:
        cells.append(f'        c.put("{combo} | Object={rn}", () -> {{ {cn} h = new {cn}(); h.f = {rinit}; return h; }});')
    cn = f"K{i}"
    L.append(f"    public static class {cn} {{ @JSONField(serializeFeatures = {{{ann}}}) public Map<Object, String> f = new LinkedHashMap<>(); }}")
    for kn, kinit in keyshapes:
        cells.append(f'        c.put("{combo} | key {kn}", () -> {{ {cn} h = new {cn}(); h.f.put({kinit}, "v"); return h; }});')
L.append("""
    static Map<String, Supplier<Object>> cells() {
        Map<String, Supplier<Object>> c = new LinkedHashMap<>();""")
L += cells
L.append("""        return c;
    }

    static String out(Object o, ObjectWriterProvider p, String ch) {
        try {
            JSONWriter.Context c = new JSONWriter.Context(p);
            String s = "json".equals(ch) ? JSON.toJSONString(o, c) : JSON.toJSONString(JSONB.parse(JSONB.toBytes(o, c)));
            return s.replaceAll("Q17\\\\$[A-Z][0-9]+(_[A-Za-z]+)?", "H");
        } catch (Throwable e) {
            return "EXC " + e.getClass().getSimpleName() + ": " + String.valueOf(e.getMessage()).replaceAll("Q17\\\\$[A-Z][0-9]+(_[A-Za-z]+)?", "H");
        }
    }

    public static void main(String[] args) {
        Map<String, Supplier<Object>> cells = cells();
        for (String ch : new String[]{"json", "jsonb"}) {
            for (Map.Entry<String, Supplier<Object>> e : cells.entrySet()) {
                String asm = out(e.getValue().get(), new ObjectWriterProvider(ObjectWriterCreatorASM.INSTANCE), ch);
                String refl = out(e.getValue().get(), new ObjectWriterProvider(ObjectWriterCreator.INSTANCE), ch);
                System.out.println(ch + " | " + e.getKey() + " || asm " + asm + " || reflect " + refl);
            }
        }
    }
}""")
out = Path(__file__).parent / "probe10" / "src" / "p17" / "Q17.java"
out.write_text("\n".join(L) + "\n")
print(len(cells), "cells per channel ->", out)
