package p17;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONB;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.annotation.JSONField;
import com.alibaba.fastjson2.annotation.JSONType;
import com.alibaba.fastjson2.writer.ObjectWriterCreator;
import com.alibaba.fastjson2.writer.ObjectWriterCreatorASM;
import com.alibaba.fastjson2.writer.ObjectWriterProvider;

import java.math.BigDecimal;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;

/**
 * Round-9 probe (generated by gen_q17.py): field-level SortFieldNamesAlphabetically combined with a second field-level
 * feature, on nested values and map keys. One line per cell (channel, combo, shape) with the ASM and the reflect output,
 * so two builds can be compared cell by cell. The reflect field writer merges the field's features into the context, so it
 * is the reference for how deep field features reach.
 */
public class Q17 {
    public enum Color { RED, GREEN }

    @JSONType(alphabetic = false)
    public static class B {
        public int z = 1;
        public String n;
        public long big = 9007199254740993L;
        public Color e = Color.RED;
        public BigDecimal d = new BigDecimal("1E+3");
        public List<String> l;
        public int zero;
        public int a = 2;
    }

    static List<B> lb() {
        return new ArrayList<>(Collections.singletonList(new B()));
    }

    static <K, V> Map<K, V> m(K k, V v) {
        return new LinkedHashMap<>(Collections.singletonMap(k, v));
    }

    public static class T0_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T0_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T0_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T0_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public List<B> f = lb(); }
    public static class T0_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public B[][] f = new B[][]{{new B()}}; }
    public static class T0_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T0_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public B f = new B(); }
    public static class O0 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public Object f; }
    public static class K0 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T1_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T1_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T1_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T1_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public List<B> f = lb(); }
    public static class T1_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public B[][] f = new B[][]{{new B()}}; }
    public static class T1_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T1_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public B f = new B(); }
    public static class O1 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public Object f; }
    public static class K1 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BeanToArray}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T2_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T2_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T2_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T2_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public List<B> f = lb(); }
    public static class T2_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public B[][] f = new B[][]{{new B()}}; }
    public static class T2_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T2_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public B f = new B(); }
    public static class O2 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public Object f; }
    public static class K2 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNulls}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T3_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T3_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T3_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T3_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public List<B> f = lb(); }
    public static class T3_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public B[][] f = new B[][]{{new B()}}; }
    public static class T3_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T3_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public B f = new B(); }
    public static class O3 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public Object f; }
    public static class K3 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteClassName}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T4_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T4_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T4_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T4_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public List<B> f = lb(); }
    public static class T4_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public B[][] f = new B[][]{{new B()}}; }
    public static class T4_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T4_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public B f = new B(); }
    public static class O4 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public Object f; }
    public static class K4 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NotWriteDefaultValue}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T5_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T5_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T5_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T5_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public List<B> f = lb(); }
    public static class T5_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public B[][] f = new B[][]{{new B()}}; }
    public static class T5_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T5_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public B f = new B(); }
    public static class O5 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public Object f; }
    public static class K5 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNonStringValueAsString}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T6_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T6_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T6_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T6_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public List<B> f = lb(); }
    public static class T6_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public B[][] f = new B[][]{{new B()}}; }
    public static class T6_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T6_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public B f = new B(); }
    public static class O6 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public Object f; }
    public static class K6 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteMapNullValue}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T7_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T7_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T7_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T7_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public List<B> f = lb(); }
    public static class T7_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public B[][] f = new B[][]{{new B()}}; }
    public static class T7_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T7_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public B f = new B(); }
    public static class O7 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public Object f; }
    public static class K7 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.ReferenceDetection}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T8_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T8_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T8_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T8_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public List<B> f = lb(); }
    public static class T8_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public B[][] f = new B[][]{{new B()}}; }
    public static class T8_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T8_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public B f = new B(); }
    public static class O8 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public Object f; }
    public static class K8 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteEnumUsingToString}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T9_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T9_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T9_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T9_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public List<B> f = lb(); }
    public static class T9_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public B[][] f = new B[][]{{new B()}}; }
    public static class T9_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T9_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public B f = new B(); }
    public static class O9 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public Object f; }
    public static class K9 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteBigDecimalAsPlain}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T10_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T10_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T10_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T10_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public List<B> f = lb(); }
    public static class T10_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public B[][] f = new B[][]{{new B()}}; }
    public static class T10_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T10_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public B f = new B(); }
    public static class O10 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public Object f; }
    public static class K10 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.BrowserCompatible}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T11_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T11_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T11_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T11_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public List<B> f = lb(); }
    public static class T11_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public B[][] f = new B[][]{{new B()}}; }
    public static class T11_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T11_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public B f = new B(); }
    public static class O11 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public Object f; }
    public static class K11 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteLongAsString}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T12_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T12_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T12_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T12_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public List<B> f = lb(); }
    public static class T12_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public B[][] f = new B[][]{{new B()}}; }
    public static class T12_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T12_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public B f = new B(); }
    public static class O12 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public Object f; }
    public static class K12 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.NullAsDefaultValue}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T13_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T13_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T13_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T13_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public List<B> f = lb(); }
    public static class T13_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public B[][] f = new B[][]{{new B()}}; }
    public static class T13_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T13_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public B f = new B(); }
    public static class O13 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public Object f; }
    public static class K13 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.WriteNullListAsEmpty}) public Map<Object, String> f = new LinkedHashMap<>(); }
    public static class T14_ListListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public List<List<B>> f = new ArrayList<>(Collections.singletonList(lb())); }
    public static class T14_AtomB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public AtomicReference<B> f = new AtomicReference<>(new B()); }
    public static class T14_OptListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public Optional<List<B>> f = Optional.of(lb()); }
    public static class T14_ListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public List<B> f = lb(); }
    public static class T14_ArrArrB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public B[][] f = new B[][]{{new B()}}; }
    public static class T14_MapListB { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public Map<String, List<B>> f = m("k", lb()); }
    public static class T14_B { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public B f = new B(); }
    public static class O14 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public Object f; }
    public static class K14 { @JSONField(serializeFeatures = {JSONWriter.Feature.SortFieldNamesAlphabetically, JSONWriter.Feature.IgnoreEmpty}) public Map<Object, String> f = new LinkedHashMap<>(); }

    static Map<String, Supplier<Object>> cells() {
        Map<String, Supplier<Object>> c = new LinkedHashMap<>();
        c.put("Sort | value List<List<B>>", T0_ListListB::new);
        c.put("Sort | value AtomicReference<B>", T0_AtomB::new);
        c.put("Sort | value Optional<List<B>>", T0_OptListB::new);
        c.put("Sort | value List<B>", T0_ListB::new);
        c.put("Sort | value B[][]", T0_ArrArrB::new);
        c.put("Sort | value Map<String, List<B>>", T0_MapListB::new);
        c.put("Sort | value B", T0_B::new);
        c.put("Sort | Object=List<List<B>>", () -> { O0 h = new O0(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort | Object=AtomicReference<B>", () -> { O0 h = new O0(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort | Object=Optional<List<B>>", () -> { O0 h = new O0(); h.f = Optional.of(lb()); return h; });
        c.put("Sort | Object=List<B>", () -> { O0 h = new O0(); h.f = lb(); return h; });
        c.put("Sort | Object=Object[]{List<B>}", () -> { O0 h = new O0(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort | Object=Map{k:List<B>}", () -> { O0 h = new O0(); h.f = m("k", lb()); return h; });
        c.put("Sort | Object=JSONArray[List<B>]", () -> { O0 h = new O0(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort | Object=B", () -> { O0 h = new O0(); h.f = new B(); return h; });
        c.put("Sort | key List<B>", () -> { K0 h = new K0(); h.f.put(lb(), "v"); return h; });
        c.put("Sort | key Optional<B>", () -> { K0 h = new K0(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort | key AtomicReference<B>", () -> { K0 h = new K0(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort | key List<List<B>>", () -> { K0 h = new K0(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort | key B", () -> { K0 h = new K0(); h.f.put(new B(), "v"); return h; });
        c.put("Sort | key B[]", () -> { K0 h = new K0(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+BeanToArray | value List<List<B>>", T1_ListListB::new);
        c.put("Sort+BeanToArray | value AtomicReference<B>", T1_AtomB::new);
        c.put("Sort+BeanToArray | value Optional<List<B>>", T1_OptListB::new);
        c.put("Sort+BeanToArray | value List<B>", T1_ListB::new);
        c.put("Sort+BeanToArray | value B[][]", T1_ArrArrB::new);
        c.put("Sort+BeanToArray | value Map<String, List<B>>", T1_MapListB::new);
        c.put("Sort+BeanToArray | value B", T1_B::new);
        c.put("Sort+BeanToArray | Object=List<List<B>>", () -> { O1 h = new O1(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+BeanToArray | Object=AtomicReference<B>", () -> { O1 h = new O1(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+BeanToArray | Object=Optional<List<B>>", () -> { O1 h = new O1(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+BeanToArray | Object=List<B>", () -> { O1 h = new O1(); h.f = lb(); return h; });
        c.put("Sort+BeanToArray | Object=Object[]{List<B>}", () -> { O1 h = new O1(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+BeanToArray | Object=Map{k:List<B>}", () -> { O1 h = new O1(); h.f = m("k", lb()); return h; });
        c.put("Sort+BeanToArray | Object=JSONArray[List<B>]", () -> { O1 h = new O1(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+BeanToArray | Object=B", () -> { O1 h = new O1(); h.f = new B(); return h; });
        c.put("Sort+BeanToArray | key List<B>", () -> { K1 h = new K1(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+BeanToArray | key Optional<B>", () -> { K1 h = new K1(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+BeanToArray | key AtomicReference<B>", () -> { K1 h = new K1(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+BeanToArray | key List<List<B>>", () -> { K1 h = new K1(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+BeanToArray | key B", () -> { K1 h = new K1(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+BeanToArray | key B[]", () -> { K1 h = new K1(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+WriteNulls | value List<List<B>>", T2_ListListB::new);
        c.put("Sort+WriteNulls | value AtomicReference<B>", T2_AtomB::new);
        c.put("Sort+WriteNulls | value Optional<List<B>>", T2_OptListB::new);
        c.put("Sort+WriteNulls | value List<B>", T2_ListB::new);
        c.put("Sort+WriteNulls | value B[][]", T2_ArrArrB::new);
        c.put("Sort+WriteNulls | value Map<String, List<B>>", T2_MapListB::new);
        c.put("Sort+WriteNulls | value B", T2_B::new);
        c.put("Sort+WriteNulls | Object=List<List<B>>", () -> { O2 h = new O2(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+WriteNulls | Object=AtomicReference<B>", () -> { O2 h = new O2(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+WriteNulls | Object=Optional<List<B>>", () -> { O2 h = new O2(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+WriteNulls | Object=List<B>", () -> { O2 h = new O2(); h.f = lb(); return h; });
        c.put("Sort+WriteNulls | Object=Object[]{List<B>}", () -> { O2 h = new O2(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+WriteNulls | Object=Map{k:List<B>}", () -> { O2 h = new O2(); h.f = m("k", lb()); return h; });
        c.put("Sort+WriteNulls | Object=JSONArray[List<B>]", () -> { O2 h = new O2(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+WriteNulls | Object=B", () -> { O2 h = new O2(); h.f = new B(); return h; });
        c.put("Sort+WriteNulls | key List<B>", () -> { K2 h = new K2(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+WriteNulls | key Optional<B>", () -> { K2 h = new K2(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+WriteNulls | key AtomicReference<B>", () -> { K2 h = new K2(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+WriteNulls | key List<List<B>>", () -> { K2 h = new K2(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+WriteNulls | key B", () -> { K2 h = new K2(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+WriteNulls | key B[]", () -> { K2 h = new K2(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+WriteClassName | value List<List<B>>", T3_ListListB::new);
        c.put("Sort+WriteClassName | value AtomicReference<B>", T3_AtomB::new);
        c.put("Sort+WriteClassName | value Optional<List<B>>", T3_OptListB::new);
        c.put("Sort+WriteClassName | value List<B>", T3_ListB::new);
        c.put("Sort+WriteClassName | value B[][]", T3_ArrArrB::new);
        c.put("Sort+WriteClassName | value Map<String, List<B>>", T3_MapListB::new);
        c.put("Sort+WriteClassName | value B", T3_B::new);
        c.put("Sort+WriteClassName | Object=List<List<B>>", () -> { O3 h = new O3(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+WriteClassName | Object=AtomicReference<B>", () -> { O3 h = new O3(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+WriteClassName | Object=Optional<List<B>>", () -> { O3 h = new O3(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+WriteClassName | Object=List<B>", () -> { O3 h = new O3(); h.f = lb(); return h; });
        c.put("Sort+WriteClassName | Object=Object[]{List<B>}", () -> { O3 h = new O3(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+WriteClassName | Object=Map{k:List<B>}", () -> { O3 h = new O3(); h.f = m("k", lb()); return h; });
        c.put("Sort+WriteClassName | Object=JSONArray[List<B>]", () -> { O3 h = new O3(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+WriteClassName | Object=B", () -> { O3 h = new O3(); h.f = new B(); return h; });
        c.put("Sort+WriteClassName | key List<B>", () -> { K3 h = new K3(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+WriteClassName | key Optional<B>", () -> { K3 h = new K3(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+WriteClassName | key AtomicReference<B>", () -> { K3 h = new K3(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+WriteClassName | key List<List<B>>", () -> { K3 h = new K3(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+WriteClassName | key B", () -> { K3 h = new K3(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+WriteClassName | key B[]", () -> { K3 h = new K3(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+NotWriteDefaultValue | value List<List<B>>", T4_ListListB::new);
        c.put("Sort+NotWriteDefaultValue | value AtomicReference<B>", T4_AtomB::new);
        c.put("Sort+NotWriteDefaultValue | value Optional<List<B>>", T4_OptListB::new);
        c.put("Sort+NotWriteDefaultValue | value List<B>", T4_ListB::new);
        c.put("Sort+NotWriteDefaultValue | value B[][]", T4_ArrArrB::new);
        c.put("Sort+NotWriteDefaultValue | value Map<String, List<B>>", T4_MapListB::new);
        c.put("Sort+NotWriteDefaultValue | value B", T4_B::new);
        c.put("Sort+NotWriteDefaultValue | Object=List<List<B>>", () -> { O4 h = new O4(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+NotWriteDefaultValue | Object=AtomicReference<B>", () -> { O4 h = new O4(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+NotWriteDefaultValue | Object=Optional<List<B>>", () -> { O4 h = new O4(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+NotWriteDefaultValue | Object=List<B>", () -> { O4 h = new O4(); h.f = lb(); return h; });
        c.put("Sort+NotWriteDefaultValue | Object=Object[]{List<B>}", () -> { O4 h = new O4(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+NotWriteDefaultValue | Object=Map{k:List<B>}", () -> { O4 h = new O4(); h.f = m("k", lb()); return h; });
        c.put("Sort+NotWriteDefaultValue | Object=JSONArray[List<B>]", () -> { O4 h = new O4(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+NotWriteDefaultValue | Object=B", () -> { O4 h = new O4(); h.f = new B(); return h; });
        c.put("Sort+NotWriteDefaultValue | key List<B>", () -> { K4 h = new K4(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+NotWriteDefaultValue | key Optional<B>", () -> { K4 h = new K4(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+NotWriteDefaultValue | key AtomicReference<B>", () -> { K4 h = new K4(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+NotWriteDefaultValue | key List<List<B>>", () -> { K4 h = new K4(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+NotWriteDefaultValue | key B", () -> { K4 h = new K4(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+NotWriteDefaultValue | key B[]", () -> { K4 h = new K4(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+WriteNonStringValueAsString | value List<List<B>>", T5_ListListB::new);
        c.put("Sort+WriteNonStringValueAsString | value AtomicReference<B>", T5_AtomB::new);
        c.put("Sort+WriteNonStringValueAsString | value Optional<List<B>>", T5_OptListB::new);
        c.put("Sort+WriteNonStringValueAsString | value List<B>", T5_ListB::new);
        c.put("Sort+WriteNonStringValueAsString | value B[][]", T5_ArrArrB::new);
        c.put("Sort+WriteNonStringValueAsString | value Map<String, List<B>>", T5_MapListB::new);
        c.put("Sort+WriteNonStringValueAsString | value B", T5_B::new);
        c.put("Sort+WriteNonStringValueAsString | Object=List<List<B>>", () -> { O5 h = new O5(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+WriteNonStringValueAsString | Object=AtomicReference<B>", () -> { O5 h = new O5(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+WriteNonStringValueAsString | Object=Optional<List<B>>", () -> { O5 h = new O5(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+WriteNonStringValueAsString | Object=List<B>", () -> { O5 h = new O5(); h.f = lb(); return h; });
        c.put("Sort+WriteNonStringValueAsString | Object=Object[]{List<B>}", () -> { O5 h = new O5(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+WriteNonStringValueAsString | Object=Map{k:List<B>}", () -> { O5 h = new O5(); h.f = m("k", lb()); return h; });
        c.put("Sort+WriteNonStringValueAsString | Object=JSONArray[List<B>]", () -> { O5 h = new O5(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+WriteNonStringValueAsString | Object=B", () -> { O5 h = new O5(); h.f = new B(); return h; });
        c.put("Sort+WriteNonStringValueAsString | key List<B>", () -> { K5 h = new K5(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+WriteNonStringValueAsString | key Optional<B>", () -> { K5 h = new K5(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+WriteNonStringValueAsString | key AtomicReference<B>", () -> { K5 h = new K5(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+WriteNonStringValueAsString | key List<List<B>>", () -> { K5 h = new K5(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+WriteNonStringValueAsString | key B", () -> { K5 h = new K5(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+WriteNonStringValueAsString | key B[]", () -> { K5 h = new K5(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+WriteMapNullValue | value List<List<B>>", T6_ListListB::new);
        c.put("Sort+WriteMapNullValue | value AtomicReference<B>", T6_AtomB::new);
        c.put("Sort+WriteMapNullValue | value Optional<List<B>>", T6_OptListB::new);
        c.put("Sort+WriteMapNullValue | value List<B>", T6_ListB::new);
        c.put("Sort+WriteMapNullValue | value B[][]", T6_ArrArrB::new);
        c.put("Sort+WriteMapNullValue | value Map<String, List<B>>", T6_MapListB::new);
        c.put("Sort+WriteMapNullValue | value B", T6_B::new);
        c.put("Sort+WriteMapNullValue | Object=List<List<B>>", () -> { O6 h = new O6(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+WriteMapNullValue | Object=AtomicReference<B>", () -> { O6 h = new O6(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+WriteMapNullValue | Object=Optional<List<B>>", () -> { O6 h = new O6(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+WriteMapNullValue | Object=List<B>", () -> { O6 h = new O6(); h.f = lb(); return h; });
        c.put("Sort+WriteMapNullValue | Object=Object[]{List<B>}", () -> { O6 h = new O6(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+WriteMapNullValue | Object=Map{k:List<B>}", () -> { O6 h = new O6(); h.f = m("k", lb()); return h; });
        c.put("Sort+WriteMapNullValue | Object=JSONArray[List<B>]", () -> { O6 h = new O6(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+WriteMapNullValue | Object=B", () -> { O6 h = new O6(); h.f = new B(); return h; });
        c.put("Sort+WriteMapNullValue | key List<B>", () -> { K6 h = new K6(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+WriteMapNullValue | key Optional<B>", () -> { K6 h = new K6(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+WriteMapNullValue | key AtomicReference<B>", () -> { K6 h = new K6(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+WriteMapNullValue | key List<List<B>>", () -> { K6 h = new K6(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+WriteMapNullValue | key B", () -> { K6 h = new K6(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+WriteMapNullValue | key B[]", () -> { K6 h = new K6(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+ReferenceDetection | value List<List<B>>", T7_ListListB::new);
        c.put("Sort+ReferenceDetection | value AtomicReference<B>", T7_AtomB::new);
        c.put("Sort+ReferenceDetection | value Optional<List<B>>", T7_OptListB::new);
        c.put("Sort+ReferenceDetection | value List<B>", T7_ListB::new);
        c.put("Sort+ReferenceDetection | value B[][]", T7_ArrArrB::new);
        c.put("Sort+ReferenceDetection | value Map<String, List<B>>", T7_MapListB::new);
        c.put("Sort+ReferenceDetection | value B", T7_B::new);
        c.put("Sort+ReferenceDetection | Object=List<List<B>>", () -> { O7 h = new O7(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+ReferenceDetection | Object=AtomicReference<B>", () -> { O7 h = new O7(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+ReferenceDetection | Object=Optional<List<B>>", () -> { O7 h = new O7(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+ReferenceDetection | Object=List<B>", () -> { O7 h = new O7(); h.f = lb(); return h; });
        c.put("Sort+ReferenceDetection | Object=Object[]{List<B>}", () -> { O7 h = new O7(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+ReferenceDetection | Object=Map{k:List<B>}", () -> { O7 h = new O7(); h.f = m("k", lb()); return h; });
        c.put("Sort+ReferenceDetection | Object=JSONArray[List<B>]", () -> { O7 h = new O7(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+ReferenceDetection | Object=B", () -> { O7 h = new O7(); h.f = new B(); return h; });
        c.put("Sort+ReferenceDetection | key List<B>", () -> { K7 h = new K7(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+ReferenceDetection | key Optional<B>", () -> { K7 h = new K7(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+ReferenceDetection | key AtomicReference<B>", () -> { K7 h = new K7(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+ReferenceDetection | key List<List<B>>", () -> { K7 h = new K7(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+ReferenceDetection | key B", () -> { K7 h = new K7(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+ReferenceDetection | key B[]", () -> { K7 h = new K7(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+WriteEnumUsingToString | value List<List<B>>", T8_ListListB::new);
        c.put("Sort+WriteEnumUsingToString | value AtomicReference<B>", T8_AtomB::new);
        c.put("Sort+WriteEnumUsingToString | value Optional<List<B>>", T8_OptListB::new);
        c.put("Sort+WriteEnumUsingToString | value List<B>", T8_ListB::new);
        c.put("Sort+WriteEnumUsingToString | value B[][]", T8_ArrArrB::new);
        c.put("Sort+WriteEnumUsingToString | value Map<String, List<B>>", T8_MapListB::new);
        c.put("Sort+WriteEnumUsingToString | value B", T8_B::new);
        c.put("Sort+WriteEnumUsingToString | Object=List<List<B>>", () -> { O8 h = new O8(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+WriteEnumUsingToString | Object=AtomicReference<B>", () -> { O8 h = new O8(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+WriteEnumUsingToString | Object=Optional<List<B>>", () -> { O8 h = new O8(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+WriteEnumUsingToString | Object=List<B>", () -> { O8 h = new O8(); h.f = lb(); return h; });
        c.put("Sort+WriteEnumUsingToString | Object=Object[]{List<B>}", () -> { O8 h = new O8(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+WriteEnumUsingToString | Object=Map{k:List<B>}", () -> { O8 h = new O8(); h.f = m("k", lb()); return h; });
        c.put("Sort+WriteEnumUsingToString | Object=JSONArray[List<B>]", () -> { O8 h = new O8(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+WriteEnumUsingToString | Object=B", () -> { O8 h = new O8(); h.f = new B(); return h; });
        c.put("Sort+WriteEnumUsingToString | key List<B>", () -> { K8 h = new K8(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+WriteEnumUsingToString | key Optional<B>", () -> { K8 h = new K8(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+WriteEnumUsingToString | key AtomicReference<B>", () -> { K8 h = new K8(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+WriteEnumUsingToString | key List<List<B>>", () -> { K8 h = new K8(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+WriteEnumUsingToString | key B", () -> { K8 h = new K8(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+WriteEnumUsingToString | key B[]", () -> { K8 h = new K8(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | value List<List<B>>", T9_ListListB::new);
        c.put("Sort+WriteBigDecimalAsPlain | value AtomicReference<B>", T9_AtomB::new);
        c.put("Sort+WriteBigDecimalAsPlain | value Optional<List<B>>", T9_OptListB::new);
        c.put("Sort+WriteBigDecimalAsPlain | value List<B>", T9_ListB::new);
        c.put("Sort+WriteBigDecimalAsPlain | value B[][]", T9_ArrArrB::new);
        c.put("Sort+WriteBigDecimalAsPlain | value Map<String, List<B>>", T9_MapListB::new);
        c.put("Sort+WriteBigDecimalAsPlain | value B", T9_B::new);
        c.put("Sort+WriteBigDecimalAsPlain | Object=List<List<B>>", () -> { O9 h = new O9(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | Object=AtomicReference<B>", () -> { O9 h = new O9(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | Object=Optional<List<B>>", () -> { O9 h = new O9(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | Object=List<B>", () -> { O9 h = new O9(); h.f = lb(); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | Object=Object[]{List<B>}", () -> { O9 h = new O9(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+WriteBigDecimalAsPlain | Object=Map{k:List<B>}", () -> { O9 h = new O9(); h.f = m("k", lb()); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | Object=JSONArray[List<B>]", () -> { O9 h = new O9(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | Object=B", () -> { O9 h = new O9(); h.f = new B(); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | key List<B>", () -> { K9 h = new K9(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | key Optional<B>", () -> { K9 h = new K9(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | key AtomicReference<B>", () -> { K9 h = new K9(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | key List<List<B>>", () -> { K9 h = new K9(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | key B", () -> { K9 h = new K9(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+WriteBigDecimalAsPlain | key B[]", () -> { K9 h = new K9(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+BrowserCompatible | value List<List<B>>", T10_ListListB::new);
        c.put("Sort+BrowserCompatible | value AtomicReference<B>", T10_AtomB::new);
        c.put("Sort+BrowserCompatible | value Optional<List<B>>", T10_OptListB::new);
        c.put("Sort+BrowserCompatible | value List<B>", T10_ListB::new);
        c.put("Sort+BrowserCompatible | value B[][]", T10_ArrArrB::new);
        c.put("Sort+BrowserCompatible | value Map<String, List<B>>", T10_MapListB::new);
        c.put("Sort+BrowserCompatible | value B", T10_B::new);
        c.put("Sort+BrowserCompatible | Object=List<List<B>>", () -> { O10 h = new O10(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+BrowserCompatible | Object=AtomicReference<B>", () -> { O10 h = new O10(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+BrowserCompatible | Object=Optional<List<B>>", () -> { O10 h = new O10(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+BrowserCompatible | Object=List<B>", () -> { O10 h = new O10(); h.f = lb(); return h; });
        c.put("Sort+BrowserCompatible | Object=Object[]{List<B>}", () -> { O10 h = new O10(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+BrowserCompatible | Object=Map{k:List<B>}", () -> { O10 h = new O10(); h.f = m("k", lb()); return h; });
        c.put("Sort+BrowserCompatible | Object=JSONArray[List<B>]", () -> { O10 h = new O10(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+BrowserCompatible | Object=B", () -> { O10 h = new O10(); h.f = new B(); return h; });
        c.put("Sort+BrowserCompatible | key List<B>", () -> { K10 h = new K10(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+BrowserCompatible | key Optional<B>", () -> { K10 h = new K10(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+BrowserCompatible | key AtomicReference<B>", () -> { K10 h = new K10(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+BrowserCompatible | key List<List<B>>", () -> { K10 h = new K10(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+BrowserCompatible | key B", () -> { K10 h = new K10(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+BrowserCompatible | key B[]", () -> { K10 h = new K10(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+WriteLongAsString | value List<List<B>>", T11_ListListB::new);
        c.put("Sort+WriteLongAsString | value AtomicReference<B>", T11_AtomB::new);
        c.put("Sort+WriteLongAsString | value Optional<List<B>>", T11_OptListB::new);
        c.put("Sort+WriteLongAsString | value List<B>", T11_ListB::new);
        c.put("Sort+WriteLongAsString | value B[][]", T11_ArrArrB::new);
        c.put("Sort+WriteLongAsString | value Map<String, List<B>>", T11_MapListB::new);
        c.put("Sort+WriteLongAsString | value B", T11_B::new);
        c.put("Sort+WriteLongAsString | Object=List<List<B>>", () -> { O11 h = new O11(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+WriteLongAsString | Object=AtomicReference<B>", () -> { O11 h = new O11(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+WriteLongAsString | Object=Optional<List<B>>", () -> { O11 h = new O11(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+WriteLongAsString | Object=List<B>", () -> { O11 h = new O11(); h.f = lb(); return h; });
        c.put("Sort+WriteLongAsString | Object=Object[]{List<B>}", () -> { O11 h = new O11(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+WriteLongAsString | Object=Map{k:List<B>}", () -> { O11 h = new O11(); h.f = m("k", lb()); return h; });
        c.put("Sort+WriteLongAsString | Object=JSONArray[List<B>]", () -> { O11 h = new O11(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+WriteLongAsString | Object=B", () -> { O11 h = new O11(); h.f = new B(); return h; });
        c.put("Sort+WriteLongAsString | key List<B>", () -> { K11 h = new K11(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+WriteLongAsString | key Optional<B>", () -> { K11 h = new K11(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+WriteLongAsString | key AtomicReference<B>", () -> { K11 h = new K11(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+WriteLongAsString | key List<List<B>>", () -> { K11 h = new K11(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+WriteLongAsString | key B", () -> { K11 h = new K11(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+WriteLongAsString | key B[]", () -> { K11 h = new K11(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+NullAsDefaultValue | value List<List<B>>", T12_ListListB::new);
        c.put("Sort+NullAsDefaultValue | value AtomicReference<B>", T12_AtomB::new);
        c.put("Sort+NullAsDefaultValue | value Optional<List<B>>", T12_OptListB::new);
        c.put("Sort+NullAsDefaultValue | value List<B>", T12_ListB::new);
        c.put("Sort+NullAsDefaultValue | value B[][]", T12_ArrArrB::new);
        c.put("Sort+NullAsDefaultValue | value Map<String, List<B>>", T12_MapListB::new);
        c.put("Sort+NullAsDefaultValue | value B", T12_B::new);
        c.put("Sort+NullAsDefaultValue | Object=List<List<B>>", () -> { O12 h = new O12(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+NullAsDefaultValue | Object=AtomicReference<B>", () -> { O12 h = new O12(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+NullAsDefaultValue | Object=Optional<List<B>>", () -> { O12 h = new O12(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+NullAsDefaultValue | Object=List<B>", () -> { O12 h = new O12(); h.f = lb(); return h; });
        c.put("Sort+NullAsDefaultValue | Object=Object[]{List<B>}", () -> { O12 h = new O12(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+NullAsDefaultValue | Object=Map{k:List<B>}", () -> { O12 h = new O12(); h.f = m("k", lb()); return h; });
        c.put("Sort+NullAsDefaultValue | Object=JSONArray[List<B>]", () -> { O12 h = new O12(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+NullAsDefaultValue | Object=B", () -> { O12 h = new O12(); h.f = new B(); return h; });
        c.put("Sort+NullAsDefaultValue | key List<B>", () -> { K12 h = new K12(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+NullAsDefaultValue | key Optional<B>", () -> { K12 h = new K12(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+NullAsDefaultValue | key AtomicReference<B>", () -> { K12 h = new K12(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+NullAsDefaultValue | key List<List<B>>", () -> { K12 h = new K12(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+NullAsDefaultValue | key B", () -> { K12 h = new K12(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+NullAsDefaultValue | key B[]", () -> { K12 h = new K12(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+WriteNullListAsEmpty | value List<List<B>>", T13_ListListB::new);
        c.put("Sort+WriteNullListAsEmpty | value AtomicReference<B>", T13_AtomB::new);
        c.put("Sort+WriteNullListAsEmpty | value Optional<List<B>>", T13_OptListB::new);
        c.put("Sort+WriteNullListAsEmpty | value List<B>", T13_ListB::new);
        c.put("Sort+WriteNullListAsEmpty | value B[][]", T13_ArrArrB::new);
        c.put("Sort+WriteNullListAsEmpty | value Map<String, List<B>>", T13_MapListB::new);
        c.put("Sort+WriteNullListAsEmpty | value B", T13_B::new);
        c.put("Sort+WriteNullListAsEmpty | Object=List<List<B>>", () -> { O13 h = new O13(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+WriteNullListAsEmpty | Object=AtomicReference<B>", () -> { O13 h = new O13(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+WriteNullListAsEmpty | Object=Optional<List<B>>", () -> { O13 h = new O13(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+WriteNullListAsEmpty | Object=List<B>", () -> { O13 h = new O13(); h.f = lb(); return h; });
        c.put("Sort+WriteNullListAsEmpty | Object=Object[]{List<B>}", () -> { O13 h = new O13(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+WriteNullListAsEmpty | Object=Map{k:List<B>}", () -> { O13 h = new O13(); h.f = m("k", lb()); return h; });
        c.put("Sort+WriteNullListAsEmpty | Object=JSONArray[List<B>]", () -> { O13 h = new O13(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+WriteNullListAsEmpty | Object=B", () -> { O13 h = new O13(); h.f = new B(); return h; });
        c.put("Sort+WriteNullListAsEmpty | key List<B>", () -> { K13 h = new K13(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+WriteNullListAsEmpty | key Optional<B>", () -> { K13 h = new K13(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+WriteNullListAsEmpty | key AtomicReference<B>", () -> { K13 h = new K13(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+WriteNullListAsEmpty | key List<List<B>>", () -> { K13 h = new K13(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+WriteNullListAsEmpty | key B", () -> { K13 h = new K13(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+WriteNullListAsEmpty | key B[]", () -> { K13 h = new K13(); h.f.put(new B[]{new B()}, "v"); return h; });
        c.put("Sort+IgnoreEmpty | value List<List<B>>", T14_ListListB::new);
        c.put("Sort+IgnoreEmpty | value AtomicReference<B>", T14_AtomB::new);
        c.put("Sort+IgnoreEmpty | value Optional<List<B>>", T14_OptListB::new);
        c.put("Sort+IgnoreEmpty | value List<B>", T14_ListB::new);
        c.put("Sort+IgnoreEmpty | value B[][]", T14_ArrArrB::new);
        c.put("Sort+IgnoreEmpty | value Map<String, List<B>>", T14_MapListB::new);
        c.put("Sort+IgnoreEmpty | value B", T14_B::new);
        c.put("Sort+IgnoreEmpty | Object=List<List<B>>", () -> { O14 h = new O14(); h.f = new ArrayList<>(Collections.singletonList(lb())); return h; });
        c.put("Sort+IgnoreEmpty | Object=AtomicReference<B>", () -> { O14 h = new O14(); h.f = new AtomicReference<>(new B()); return h; });
        c.put("Sort+IgnoreEmpty | Object=Optional<List<B>>", () -> { O14 h = new O14(); h.f = Optional.of(lb()); return h; });
        c.put("Sort+IgnoreEmpty | Object=List<B>", () -> { O14 h = new O14(); h.f = lb(); return h; });
        c.put("Sort+IgnoreEmpty | Object=Object[]{List<B>}", () -> { O14 h = new O14(); h.f = new Object[]{lb()}; return h; });
        c.put("Sort+IgnoreEmpty | Object=Map{k:List<B>}", () -> { O14 h = new O14(); h.f = m("k", lb()); return h; });
        c.put("Sort+IgnoreEmpty | Object=JSONArray[List<B>]", () -> { O14 h = new O14(); h.f = com.alibaba.fastjson2.JSONArray.of(lb()); return h; });
        c.put("Sort+IgnoreEmpty | Object=B", () -> { O14 h = new O14(); h.f = new B(); return h; });
        c.put("Sort+IgnoreEmpty | key List<B>", () -> { K14 h = new K14(); h.f.put(lb(), "v"); return h; });
        c.put("Sort+IgnoreEmpty | key Optional<B>", () -> { K14 h = new K14(); h.f.put(Optional.of(new B()), "v"); return h; });
        c.put("Sort+IgnoreEmpty | key AtomicReference<B>", () -> { K14 h = new K14(); h.f.put(new AtomicReference<>(new B()), "v"); return h; });
        c.put("Sort+IgnoreEmpty | key List<List<B>>", () -> { K14 h = new K14(); h.f.put(new ArrayList<>(Collections.singletonList(lb())), "v"); return h; });
        c.put("Sort+IgnoreEmpty | key B", () -> { K14 h = new K14(); h.f.put(new B(), "v"); return h; });
        c.put("Sort+IgnoreEmpty | key B[]", () -> { K14 h = new K14(); h.f.put(new B[]{new B()}, "v"); return h; });
        return c;
    }

    static String out(Object o, ObjectWriterProvider p, String ch) {
        try {
            JSONWriter.Context c = new JSONWriter.Context(p);
            String s = "json".equals(ch) ? JSON.toJSONString(o, c) : JSON.toJSONString(JSONB.parse(JSONB.toBytes(o, c)));
            return s.replaceAll("Q17\\$[A-Z][0-9]+(_[A-Za-z]+)?", "H");
        } catch (Throwable e) {
            return "EXC " + e.getClass().getSimpleName() + ": " + String.valueOf(e.getMessage()).replaceAll("Q17\\$[A-Z][0-9]+(_[A-Za-z]+)?", "H");
        }
    }

    public static void main(String[] args) {
        Map<String, Supplier<Object>> cells = cells();
        for (String ch : new String[]{"json", "jsonb"}) {
            for (Map.Entry<String, Supplier<Object>> e : cells.entrySet()) {
                String asm = out(e.getValue().get(), new ObjectWriterProvider(ObjectWriterCreatorASM.INSTANCE), ch);
                String refl = out(e.getValue().get(), new ObjectWriterProvider(ObjectWriterCreator.INSTANCE), ch);
                System.out.println(ch + " | " + e.getKey() + " || asm " + asm + " || reflect " + refl);
            }
        }
    }
}
