package p24;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONB;
import com.alibaba.fastjson2.JSONWriter;
import com.alibaba.fastjson2.annotation.JSONField;
import com.alibaba.fastjson2.annotation.JSONType;
import com.alibaba.fastjson2.filter.ValueFilter;
import com.alibaba.fastjson2.writer.ObjectWriterCreator;
import com.alibaba.fastjson2.writer.ObjectWriterCreatorASM;
import com.alibaba.fastjson2.writer.ObjectWriterProvider;

import java.util.*;

/** Writer-side changes of 575bd9fa2: filtered map values, registered generated writers, keys and $ref, direct-JIT list bail. */
public class Q24 {
    static final JSONWriter.Feature SORT = JSONWriter.Feature.SortFieldNamesAlphabetically;

    // (b) a Map writer's own FieldBased under a filter
    public static class FB {
        private int x = 1;
        public int getY() { return 2; }
    }
    public static class FBHolder {
        @JSONField(serializeFeatures = JSONWriter.Feature.FieldBased)
        public Map<String, FB> m = new LinkedHashMap<>(Collections.singletonMap("k", new FB()));
    }

    // (c) a registered writer generated by the ASM creator
    @JSONType(alphabetic = false)
    public static class Z {
        public int zeta = 1;
        public int alpha = 2;
    }

    // (e) bean keys and ReferenceDetection
    @JSONType(alphabetic = false)
    public static class K {
        public int zk;
        public int ak;
        K(int v) { zk = v; ak = v; }
    }
    @JSONType(alphabetic = false)
    public static class V {
        public int zv = 1;
        public int av = 2;
    }

    // (f) direct-JIT list writer under an annotation-level sort
    @JSONType(alphabetic = false)
    public static class C {
        public int zulu = 7;
        public int alpha = 1;
    }
    @JSONType(serializeFeatures = JSONWriter.Feature.SortFieldNamesAlphabetically)
    public static class SortedHolder {
        public List<C> items = new ArrayList<>(Collections.singletonList(new C()));
    }

    static String s(Runnable r) {
        try {
            r.run();
            return "";
        } catch (Throwable e) {
            return "EXC " + e.getClass().getSimpleName();
        }
    }

    static String json(Object o, JSONWriter.Context c) {
        try {
            return JSON.toJSONString(o, c);
        } catch (Throwable e) {
            return "EXC " + e.getClass().getSimpleName();
        }
    }

    static String jsonb(Object o, JSONWriter.Context c) {
        try {
            return JSON.toJSONString(JSONB.parse(JSONB.toBytes(o, c)));
        } catch (Throwable e) {
            return "EXC " + e.getClass().getSimpleName();
        }
    }

    public static void main(String[] args) {
        for (ObjectWriterCreator creator : new ObjectWriterCreator[]{ObjectWriterCreatorASM.INSTANCE, ObjectWriterCreator.INSTANCE}) {
            String cn = creator == ObjectWriterCreator.INSTANCE ? "reflect" : "asm";
            // (b)
            {
                ObjectWriterProvider p = new ObjectWriterProvider(creator);
                JSONWriter.Context plain = new JSONWriter.Context(p);
                JSONWriter.Context filtered = new JSONWriter.Context(p);
                filtered.setValueFilter((ValueFilter) (o, n, v) -> v);
                System.out.println(cn + "\tb field FieldBased map value\tno filter=" + json(new FBHolder(), plain) + "\twith filter=" + json(new FBHolder(), filtered));
            }
            // (c)
            {
                ObjectWriterProvider p = new ObjectWriterProvider(creator);
                p.register(Z.class, ObjectWriterCreatorASM.INSTANCE.createObjectWriter(Z.class));
                System.out.println(cn + "\tc registered ASM-generated writer\tnatural=" + json(new Z(), new JSONWriter.Context(p))
                        + "\tsorted=" + json(new Z(), new JSONWriter.Context(p, SORT))
                        + "\tsorted JSONB=" + jsonb(new Z(), new JSONWriter.Context(p, SORT))
                        + "\tsorted list=" + json(Collections.singletonList(new Z()), new JSONWriter.Context(p, SORT)));
                ObjectWriterProvider q = new ObjectWriterProvider(creator);
                q.register(Z.class, ObjectWriterCreator.INSTANCE.createObjectWriter(Z.class));
                System.out.println(cn + "\tc registered reflect-created writer\tnatural=" + json(new Z(), new JSONWriter.Context(q))
                        + "\tsorted=" + json(new Z(), new JSONWriter.Context(q, SORT)));
            }
            // (e)
            {
                V shared = new V();
                Map<Object, Object> two = new LinkedHashMap<>();
                two.put(new K(1), shared);
                two.put(new K(2), shared);
                Map<String, Object> strKeys = new LinkedHashMap<>();
                strKeys.put("a", shared);
                strKeys.put("b", shared);
                for (boolean sort : new boolean[]{false, true}) {
                    ObjectWriterProvider p = new ObjectWriterProvider(creator);
                    JSONWriter.Context c = sort
                            ? new JSONWriter.Context(p, JSONWriter.Feature.ReferenceDetection, SORT)
                            : new JSONWriter.Context(p, JSONWriter.Feature.ReferenceDetection);
                    System.out.println(cn + "\te bean keys, ReferenceDetection" + (sort ? " + sort" : "") + "\tshared value=" + json(two, c)
                            + "\tstring keys=" + json(strKeys, c));
                }
            }
            // (f)
            for (String order : new String[]{"cold", "warm"}) {
                ObjectWriterProvider p = new ObjectWriterProvider(creator);
                if ("warm".equals(order)) {
                    json(new C(), new JSONWriter.Context(p));
                    jsonb(new C(), new JSONWriter.Context(p));
                }
                System.out.println(cn + "\tf @JSONType sort holder, List<C> (" + order + ")\tjson=" + json(new SortedHolder(), new JSONWriter.Context(p))
                        + "\tjsonb=" + jsonb(new SortedHolder(), new JSONWriter.Context(p))
                        + "\tjsonb BeanToArray=" + jsonb(new SortedHolder(), new JSONWriter.Context(p, JSONWriter.Feature.BeanToArray)));
            }
        }
    }
}
